# Generated by Django 5.2.14 on 2026-05-12 16:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок статьи', max_length=200, verbose_name='Заголовок')),
                ('short_content', models.TextField(help_text='Краткое описание статьи (до 500 символов)', max_length=500, verbose_name='Краткое содержание')),
                ('full_content', models.TextField(help_text='Полный текст статьи', verbose_name='Полное содержание')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_date'],
            },
        ),
    ]
